# Generated by Django 2.0 on 2019-03-31 19:50

from django.db import migrations, models
import tesseractfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('p_content', models.TextField(verbose_name='Primany Content')),
                ('s_content', tesseractfield.fields.TesseractField(verbose_name='Second Content')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['title'],
            },
        ),
    ]
